
server:
  port: 8081

person:
   age: 18
logging:
  level:
    com.ydm: debug
# 默认日志文件名
#  file: G:/TEST.log
# 默认日志路径  当前磁盘根目录生成日志文件
#  path: /spring/log
# logback.xml路径，默认为classpath:logback.xml
# config: ./logback.xml
  pattern:
#  日志文件打印格式
#   file: %d{yyyy-mm-dd HH:mm:ss:SSS} ===[%thread] %-5level %logger{50} -%ms%n
#   控制台日志格式
#    console: "%d{yyyy-mm-dd HH:mm:ss:SSS} ====[%thread] %-5level %logger{50} -%ms%n"

spring:
  datasource:
    username: root
    password: P@ssw0rd
    url: jdbc:mysql://localhost:3306/ydm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true


#模板引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
mybatis:
    mapper-locations: classpath:mapping/*.xml


#elaticjob:
# zookeeper:
#  server-lists: 39.97.105.105:2181
#  namespace: my-project


